import {
  Button,
  Card,
  Container,
  Image,
  Text,
  SimpleGrid,
  Title,
} from "@mantine/core";
import type { NextPage } from "next";
import { useSession, signIn } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data } = useSession();

  const { data: posts, isLoading } = trpc.useQuery(["posts.get-all"]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <SimpleGrid cols={3}>
          {posts?.map((post) => {
            const id = Math.round(Math.random() * 1000);
            return (
              <Card shadow="sm" p="lg" radius="md" withBorder key={post.id}>
                <Card.Section>
                  <Image
                    src={`https://picsum.photos/id/${id}/300/160`}
                    height={160}
                    alt="Norway"
                  />
                </Card.Section>

                <Title order={3}>{post.title}</Title>
                <Link href={`/posts/${post.permalink}`} passHref>
                  <Button
                    component="a"
                    variant="light"
                    color="blue"
                    fullWidth
                    mt="md"
                    radius="md"
                  >
                    Read post
                  </Button>
                </Link>
              </Card>
            );
          })}
        </SimpleGrid>
      </Container>
    </>
  );
};

export default Home;
